//Constants for getting type references
export const REGISTRO_PAGE = 'RegistroPage';
export const LOGIN_PAGE = 'LoginPage';
export const PEDIDO_NUEVO = 'PedidoPage';
export const DIRECCIONES_PAGE = 'DireccionesPage';
export const DIRECCION_PAGE = 'DireccionPage';
export const MISDATOS_PAGE = 'MisdatosPage';
export const PEDIDOS_PAGE = 'PedidosPage';
export const GRAFICAS_PAGE = 'GraficasPage';
export const ALERTAS_PAGE = 'AlertasPage';